layout_spectrum: 0.2297872
name: Urayoan
color:
  brandStrength: 0.3340425
  saturation: 0.299076
  brandColors:
    - '#393930'
    - '#030302'
    - '#77A5C4'
    - '#5C6F87'
    - '#885331'
  lightness: 0.263375
  rhythmicContrast: 0.8948262
typography_spectrum: 0.1441504
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
