layout_spectrum: 0.1886799
typography_spectrum: 0.1441504
color:
  lightness: 0.263375
  brandStrength: 0.1341562
  saturation: 0.299076
  rhythmicContrast: 0.8948262
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Urayoan
